<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>SmartStandards.Logging.AspSupport</AssemblyName>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Logging</RootNamespace>
    <OutputPath>..\..\dist\bin-net10.0\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <DocumentationFile>..\..\dist\bin-net10.0\SmartStandards.Logging.AspSupport.xml</DocumentationFile>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SmartStandards.Logging.Tests" />
  </ItemGroup>

  <ItemGroup>
  
    <!-- IMPORTANT: this package is made for the ASP.NET Core ecosystem ONLY -->
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    
    <!-- <PackageReference Include="SmartStandards.WebApiDependencies.AspNetCore.net10.0" Version="10.0.0" /> --> 
    <!-- <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.6" /> -->
    <!-- <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="9.0.6" /> -->
    <!-- <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.4" /> -->
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />

  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartStandards.Logging.Centralized.net10.0\SmartStandards.Logging.Centralized.net10.0.csproj" />
  </ItemGroup>

 <Import Project="..\SmartStandards.Logging.AspSupport\SmartStandards.Logging.AspSupport.projitems" Label="Shared" />

</Project>
